deploy-job:
  docker:
    - image: my-image-version-tag
  working_directory: /tmp/my-project
  steps:
    - run:
        name: Deploy Master to Firebase
        command: npm run deploy

workflows:
  version: 2

  -deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
